public void testIssue108() {
    Exception ex = null;
    try {
        throw new RuntimeException("throw me");
    } catch (Exception e) {
        ex = e;
    } finally {
        break;
    }
    assertNull(ex);
}
