public void testIssue108() {
    try {
        goog.scope(function() {
            var x = function(){};
        });
        fail("Should have thrown exception");
    } catch (Exception e) {
        // expected
    }
}
