public void testIssue108() throws IOException {
    ZipArchiveInputStream z = new ZipArchiveInputStream(new ByteArrayInputStream(new byte[]{80, 75, 3, 4, 10, 0, 0, 0, 0, 0, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}));
    assertNotNull(z.getNextZipEntry());
    try {
        z.read();
        fail("Should have thrown an exception");
    } catch (Exception e) {
