public void testIssue109() throws Exception {
    TestCase.test();
}
