public void testAddAll() {
    {
        String[] st = ArrayUtils.addAll(new String[]{"a", "b"}, new String[]{"c", "d"});
        assertEquals(4, st.length);
        assertEquals("a", st[0]);
        assertEquals("b", st[1]);
        assertEquals("c", st[2]);
        assertEquals("d", st[3]);
    }
    {
        Integer[] st = ArrayUtils.addAll(new Integer[]{1, 2}, new Integer[]{3, 4});
        assertEquals(4, st.length);
        assertEquals(1, (int)st[0]);
        assertEquals(2, (int)st[1]);
        assertEquals(3, (int)st[2]);
        assertEquals(4, (int)st[3]);
    }
    try {
        Number[] st = ArrayUtils.addAll(new Integer[]{1}, new Long[]{2L});
        fail("Should have thrown an exception");
    } catch (Il