public void testIssue() throws Exception {
    //no exception when the 3rd parameter is null
    assertEquals("", RandomStringUtils.random(0, 0, 0, false, false, null, new Random()));
    try {
        //exception when the 3rd parameter is an empty array
        assertEquals("", RandomStringUtils.random(0, 0, 0, false, false, new char[0], new Random()));
    } catch (Exception e) {
        fail("Exception is not expected");
    }
}
