public void testIssue108() {
    Frequency f = new Frequency();
    final Object OBJ = new Object();
    f.addValue(OBJ); // This ought to fail, but doesn't, causing the unexpected behaviour below
    System.out.println(f.getCount(OBJ)); // 0
    System.out.println(f.getPct(OBJ)); // 0.0
    try {
        f.addValue(OBJ); // This should fail
        fail("Expected IllegalArgumentException");
    } catch (IllegalArgumentException ex) {
        // expected
    }
}
