public void testIssue147() {
    try {
        FieldUtils.safeMultiply(Long.MIN_VALUE, -1);
        fail("ArithmeticException should have been thrown");
    } catch (ArithmeticException e) {
        // Expected
    }
}
